blank_issues_enabled: true
contact_links:
  - name: Contact
    url: https://www.rnalab.ca
    about: Get in touch for anything related to Open Virome. Send an email to rnabased.lifeforms@gmail.com.
  - name: Want to work with us?
    url: https://www.rnalab.ca/join
    about: Want to work with us? Check out our website!
