blank_issues_enabled: true
contact_links:
  - name: Contact
    url: rnabased.lifeforms@gmail.com
    about: Get in touch for anything related to Open Virome
  - name: Want to work with us?
    url: https://www.rnalab.ca/join
    about: Want to work with us? Check out our website!
